# Generated by Django 2.2.6 on 2019-12-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=50)),
                ('experiment', models.CharField(max_length=50)),
                ('alien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Alien')),
            ],
        ),
    ]
