# Generated by Django 2.2.6 on 2019-12-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ufo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='ufos',
            field=models.ManyToManyField(to='main_app.Ufo'),
        ),
    ]
